[package]
name = "engine"
version = "0.0.0"
authors = ["Josh Cooper <josh@cooper.is>"]
edition = "2018"

[dependencies]
thiserror = "1"
derive_more = "0.99"
rust_decimal = "1"
csv = "1"
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
rust_decimal_macros = "1"
