#!/usr/bin/env python3

# === Script to generate random transactions. ===
# No attempt is made to produce a coherent set of transactions, so multi-step
# state transitions such as deposit -> dispute -> chargeback probably won't be
# produced. This script is more for quickly generating a large set of data.

import sys
import random

def generate_transaction():
    ty = random.choice(["deposit", "withdrawal", "dispute", "resolve", "chargeback"])
    client = random.randint(0, 0xffff)
    tx = random.randint(0, 0xffffffff)
    amount = round(random.uniform(0, 1e6), 4)

    if ty == "deposit" or ty == "withdrawal":
        return f"{ty},{client},{tx},{amount}"
    else:
        return f"{ty},{client},{tx}"

n = int(sys.argv[1]) if len(sys.argv) > 1 else 1

print("type,client,tx,amount")

for i in range(0, n):
    print(generate_transaction())
